import type { Week } from "@/lib/content-types";

// Week 11 — third week of the Sujuvuus phase (weeks 9–13), broadening into applied and
// specialised B1–B2 vocabulary: science & research, economy & consumption, emotions &
// experience, health & body, environment & nature, and media/information/technology. The
// reading text uses only words that already exist in the corpus (Weeks 1–11).
const week11: Week = {
  week: 11,
  phase: "Sujuvuus",
  theme: "Tiede, talous ja kestävä tulevaisuus",
  days: [
    {
      day: 1,
      theme: "Tiede ja tutkimus",
      wordSlugs: [
        "tiede",
        "tutkimus",
        "tutkija",
        "tulos",
        "menetelmä",
        "teoria",
        "mitata",
        "osoittaa",
        "tieteellinen",
        "löytö",
        "aineisto",
        "julkaista",
      ],
    },
    {
      day: 2,
      theme: "Talous ja kuluttaminen",
      wordSlugs: [
        "markkinat",
        "kysyntä",
        "tarjonta",
        "kuluttaa",
        "kuluttaja",
        "tuottaa",
        "tuotanto",
        "voitto",
        "kustannus",
        "kallistua",
        "vero",
        "sijoitus",
      ],
    },
    {
      day: 3,
      theme: "Tunteet ja kokemukset",
      wordSlugs: [
        "pettymys",
        "helpotus",
        "jännitys",
        "innostus",
        "innostua",
        "pelottaa",
        "harmittaa",
        "kaivata",
        "ikävä",
        "tuntua",
        "kokea",
        "järkyttyä",
      ],
    },
    {
      day: 4,
      theme: "Terveys ja keho",
      wordSlugs: [
        "hengittää",
        "levätä",
        "lepo",
        "liikkua",
        "hyvinvointi",
        "loukkaantua",
        "vamma",
        "oire",
        "tartunta",
        "hoito",
        "jaksaa",
        "kunto",
      ],
    },
    {
      day: 5,
      theme: "Ympäristö ja luonto",
      wordSlugs: [
        "saaste",
        "suojella",
        "suojelu",
        "kierrättää",
        "jäte",
        "energia",
        "kestävä",
        "päästö",
        "lämpötila",
        "säilyttää",
        "saastua",
        "luonnonvara",
      ],
    },
    {
      day: 6,
      theme: "Media, tieto ja teknologia",
      wordSlugs: [
        "tiedosto",
        "sovellus",
        "verkko",
        "tallentaa",
        "poistaa",
        "asentaa",
        "päivittää",
        "tekoäly",
        "lähde",
        "selain",
        "käynnistää",
        "tietoturva",
      ],
    },
  ],
  teksti: {
    title: "Tutkijan löytö",
    level: "B1",
    topic: "Nuori tutkija kehittää tekoälysovelluksen, tutkii sen vaikutusta päästöihin ja oppii, että hyvinvointi ja luonnon suojelu kulkevat käsi kädessä.",
    paragraph:
      "Nuori [[tutkija]] Liisa oli kiinnostunut siitä, miten [[tekoäly]] voisi auttaa [[suojelemaan]] [[ympäristöä]]. Hän aloitti [[tutkimuksen]], jonka [[tavoitteena]] oli [[mitata]], paljonko ihmiset [[kuluttavat]] [[energiaa]] kotona. [[Tiede]] oli kiinnostanut häntä jo lapsena. " +
      "Liisa [[kehitti]] [[sovelluksen]], joka [[tallentaa]] tiedot [[verkkoon]] ja antaa [[kuluttajalle]] vinkkejä. Hän [[asensi]] [[selaimeen]] lisäosan ja [[päivitti]] [[tiedostot]] joka viikko. [[Tietoturva]] oli tärkeää, jotta käyttäjien tiedot [[säilyisivät]] turvassa. " +
      "Kun Liisa [[mittasi]] [[tulokset]], [[tieteellinen]] [[aineisto]] [[osoitti]], että [[sovellus]] [[vähensi]] [[päästöjä]]. [[Menetelmä]] oli luotettava. Aluksi [[tulokset]] [[pelottivat]] häntä, mutta lopulta hän tunsi suurta [[helpotusta]] ja [[innostusta]]. " +
      "[[Markkinoilla]] oli [[kysyntää]] tällaisille [[sovelluksille]], joten yritys kasvatti [[tarjontaa]] ja teki [[sijoituksen]] hankkeeseen. Vaikka [[kustannukset]] olivat aluksi suuret eikä [[voittoa]] heti syntynyt, [[kestävä]] [[kysyntä]] kasvoi koko ajan. " +
      "Liisan [[löytö]] sai muutkin [[innostumaan]] ja [[suojelemaan]] [[luonnonvaroja]] sekä [[kierrättämään]] enemmän. Hän [[julkaisi]] [[tutkimuksensa]], ja se [[tuntui]] hienolta. Tärkeintä oli, että ihmisten [[hyvinvointi]] ja [[luonnon]] [[suojelu]] voivat kulkea käsi kädessä – kunhan muistaa myös [[levätä]] [[välillä]].",
    translation:
      "Young researcher Liisa was interested in how artificial intelligence could help protect the environment. She started a study whose goal was to measure how much energy people consume at home. Science had fascinated her already as a child. " +
      "Liisa developed an app that saves the data to the cloud and gives the consumer tips. She installed an add-on in the browser and updated the files every week. Information security was important, so that users' data would stay safe. " +
      "When Liisa measured the results, the scientific data showed that the app reduced emissions. The method was reliable. At first the results scared her, but in the end she felt great relief and enthusiasm. " +
      "There was demand on the market for apps like this, so the company increased its supply and made an investment in the project. Although the costs were high at first and no profit appeared right away, the sustained demand kept growing all the time. " +
      "Liisa's discovery got others excited too about protecting natural resources and recycling more. She published her study, and it felt wonderful. The most important thing was that people's well-being and the protection of nature can go hand in hand — as long as one also remembers to rest now and then.",
    targets: [
      "tutkija",
      "tekoäly",
      "suojella",
      "ympäristö",
      "tutkimus",
      "tavoite",
      "mitata",
      "kuluttaa",
      "energia",
      "tiede",
      "kehittää",
      "sovellus",
      "tallentaa",
      "verkko",
      "kuluttaja",
      "asentaa",
      "selain",
      "päivittää",
      "tiedosto",
      "tietoturva",
      "säilyttää",
      "tulos",
      "tieteellinen",
      "aineisto",
      "osoittaa",
      "vähentää",
      "päästö",
      "menetelmä",
      "pelottaa",
      "helpotus",
      "innostus",
      "markkinat",
      "kysyntä",
      "tarjonta",
      "sijoitus",
      "kustannus",
      "voitto",
      "kestävä",
      "löytö",
      "innostua",
      "luonnonvara",
      "kierrättää",
      "julkaista",
      "tuntua",
      "hyvinvointi",
      "luonto",
      "suojelu",
      "levätä",
      "välillä",
    ],
  },
};

export default week11;
