import type { Week } from "@/lib/content-types";

// Week 5 — first week of the Laajennus phase (weeks 5–8), expanding vocabulary
// toward B1: mental & communication verbs, handling/movement verbs, emotions &
// character, abstract concepts, change verbs, and work/economy nouns. The reading
// text uses only words that already exist in the corpus.
const week5: Week = {
  week: 5,
  phase: "Laajennus",
  theme: "Ajattelu, toiminta ja yhteiskunta",
  days: [
    {
      day: 1,
      theme: "Mieli ja viestintä",
      wordSlugs: [
        "uskoa",
        "toivoa",
        "luulla",
        "tarkoittaa",
        "päättää",
        "huomata",
        "selittää",
        "pyytää",
        "vastata",
        "kiittää",
        "esittää",
        "ehdottaa",
      ],
    },
    {
      day: 2,
      theme: "Käsittely ja liike",
      wordSlugs: [
        "nostaa",
        "laskea",
        "vetää",
        "työntää",
        "heittää",
        "kantaa",
        "panna",
        "siirtää",
        "kääntää",
        "pudota",
        "tarttua",
        "kaataa",
      ],
    },
    {
      day: 3,
      theme: "Tunteet ja luonne",
      wordSlugs: [
        "onni",
        "ilo",
        "suru",
        "pelko",
        "tunne",
        "rakkaus",
        "rohkea",
        "ystävällinen",
        "kiltti",
        "rehellinen",
        "ahkera",
        "laiska",
      ],
    },
    {
      day: 4,
      theme: "Abstraktit käsitteet",
      wordSlugs: [
        "asia",
        "syy",
        "tapa",
        "ongelma",
        "esimerkki",
        "ero",
        "keino",
        "tilanne",
        "mahdollisuus",
        "vaikutus",
        "merkitys",
        "kokemus",
      ],
    },
    {
      day: 5,
      theme: "Muutos ja kehitys",
      wordSlugs: [
        "muuttua",
        "kehittää",
        "lisätä",
        "vähentää",
        "kasvattaa",
        "riittää",
        "jatkaa",
        "jakaa",
        "kerätä",
        "yhdistää",
        "parantaa",
        "säästää",
      ],
    },
    {
      day: 6,
      theme: "Työ ja talous",
      wordSlugs: [
        "palkka",
        "asiakas",
        "yritys",
        "kokous",
        "ala",
        "palvelu",
        "tuote",
        "johtaja",
        "työntekijä",
        "sopimus",
        "talous",
        "lasku",
      ],
    },
  ],
  teksti: {
    title: "Rohkea päätös",
    level: "B1",
    topic: "Sami kertoo, miksi hän vaihtoi alaa ja mitä rohkeudesta seurasi.",
    paragraph:
      "Viime vuonna [[päätin]] [[muuttaa]] elämääni. Olin tehnyt samaa työtä kauan, [[mutta]] halusin [[kehittää]] itseäni ja [[oppia]] uutta. [[Uskoin]], että minulla on [[mahdollisuus]] vaihtaa [[alaa]]. Se oli [[rohkea]] valinta, [[koska]] vanha työ oli turvallinen. " +
      "Hain töitä uudesta [[yrityksestä]] ja [[yritin]] olla [[rehellinen]] haastattelussa. Uutena [[työntekijänä]] minulla oli paljon [[kysymyksiä]]. [[Joskus]] [[tilanne]] oli vaikea, [[jos]] [[asiakas]] oli [[vihainen]], [[mutta]] [[yleensä]] työ toi [[iloa]]. " +
      "Pian [[huomasin]], että [[kokemus]] [[kasvaa]] nopeasti, [[kun]] [[yrittää]] joka päivä. [[Tärkein]] [[asia]] on, että [[tunnen]] itseni [[iloiseksi]]. Olen [[kiittänyt]] itseäni monta kertaa: [[muutuin]] [[rohkeammaksi]] ihmiseksi.",
    translation:
      "Last year I decided to change my life. I had done the same job for a long time, but I wanted to develop myself and learn something new. I believed that I had a chance to change fields. It was a brave choice, because the old job was safe. " +
      "I applied for work at a new company and tried to be honest in the interview. As a new employee, I had a lot of questions. Sometimes the situation was difficult, if a customer was angry, but usually the work brought joy. " +
      "Soon I noticed that experience grows quickly when you try every day. The most important thing is that I feel happy. I have thanked myself many times: I became a braver person.",
    targets: [
      "päättää",
      "muuttaa",
      "mutta",
      "kehittää",
      "oppia",
      "uskoa",
      "mahdollisuus",
      "ala",
      "rohkea",
      "koska",
      "yritys",
      "yrittää",
      "rehellinen",
      "työntekijä",
      "kysymys",
      "joskus",
      "tilanne",
      "jos",
      "asiakas",
      "vihainen",
      "yleensä",
      "ilo",
      "huomata",
      "kokemus",
      "kasvaa",
      "kun",
      "tärkeä",
      "asia",
      "tuntea",
      "iloinen",
      "kiittää",
      "muuttua",
    ],
  },
};

export default week5;
