import type { Week } from "@/lib/content-types";

// Week 6 — second week of the Laajennus phase (weeks 5–8), expanding vocabulary
// toward B1: communication & language, society & power, nature & environment,
// body & health, movement & travel, and free time & culture. The reading text
// uses only words that already exist in the corpus (Weeks 1–6).
const week6: Week = {
  week: 6,
  phase: "Laajennus",
  theme: "Maailma, yhteiskunta ja vapaa-aika",
  days: [
    {
      day: 1,
      theme: "Viestintä ja kieli",
      wordSlugs: [
        "sana",
        "kieli",
        "uutinen",
        "lehti",
        "viesti",
        "ääni",
        "keskustella",
        "mainita",
        "ilmoittaa",
        "kuvata",
        "kutsua",
        "neuvoa",
      ],
    },
    {
      day: 2,
      theme: "Yhteiskunta ja valta",
      wordSlugs: [
        "valtio",
        "hallitus",
        "laki",
        "yhteiskunta",
        "kansa",
        "raja",
        "valta",
        "oikeus",
        "päätös",
        "äänestää",
        "vaikuttaa",
        "järjestää",
      ],
    },
    {
      day: 3,
      theme: "Luonto ja ympäristö",
      wordSlugs: [
        "luonto",
        "maailma",
        "eläin",
        "kasvi",
        "ympäristö",
        "ranta",
        "saari",
        "pilvi",
        "tähti",
        "kukka",
        "vuori",
        "ilmasto",
      ],
    },
    {
      day: 4,
      theme: "Keho ja terveys",
      wordSlugs: [
        "keho",
        "veri",
        "hammas",
        "selkä",
        "sormi",
        "voima",
        "lääke",
        "sairaus",
        "vatsa",
        "hius",
        "terveellinen",
        "parantua",
      ],
    },
    {
      day: 5,
      theme: "Liike ja matkustus",
      wordSlugs: [
        "matkustaa",
        "lentää",
        "laiva",
        "pyörä",
        "lippu",
        "reitti",
        "nopeus",
        "saapua",
        "kulkea",
        "pysähtyä",
        "jättää",
        "kuljettaa",
      ],
    },
    {
      day: 6,
      theme: "Vapaa-aika ja kulttuuri",
      wordSlugs: [
        "harrastus",
        "peli",
        "elokuva",
        "musiikki",
        "laulu",
        "kuva",
        "taide",
        "pelata",
        "voittaa",
        "juhla",
        "urheilu",
        "tanssia",
      ],
    },
  ],
  teksti: {
    title: "Viikonloppu luonnossa",
    level: "B1",
    topic: "Anna kertoo, miten uutinen ilmastosta sai hänet matkustamaan ystävien kanssa luontoon.",
    paragraph:
      "Luin eilen [[lehdestä]] [[uutisen]], joka [[vaikutti]] minuun voimakkaasti. Siinä [[kuvattiin]], miten [[ilmasto]] muuttuu ja miten se koskee koko [[maailmaa]]. [[Ympäristö]] on minulle tärkeä [[asia]], ja [[ajattelin]] pitkään, mitä voisin tehdä. Lopulta päätin [[matkustaa]] viikonlopuksi lähelle [[luontoa]]. " +
      "[[Kutsuin]] kaksi [[ystävää]] mukaan ja [[ehdotin]], että [[lähdemme]] [[junalla]]. Ostimme [[liput]] netistä, ja juna [[kulki]] hyvää vauhtia. [[Saavuimme]] pienelle [[saarelle]] iltapäivällä. Taivaalla [[lensi]] lintuja, [[rannalla]] kasvoi [[kukkia]] ja kaukana näkyi korkea [[vuori]]. " +
      "Illalla [[järjestimme]] pienet [[juhlat]]. Kuuntelimme [[musiikkia]] ja [[tanssimme]] myöhään asti. [[Keskustelimme]] myös vakavista asioista: [[yhteiskunnasta]], [[laista]] ja siitä, miksi kannattaa [[äänestää]]. Jokaisella on [[oikeus]] [[vaikuttaa]] yhteisiin [[päätöksiin]]. " +
      "Sunnuntaina [[keho]] oli väsynyt, mutta olo [[parantui]] nopeasti. [[Huomasin]], että [[terveellinen]] elämä ei ole vain [[lääke]] ja [[urheilu]], vaan myös [[luonto]], [[ystävät]] ja [[ilo]]. Ennen kotimatkaa otin vielä [[kuvan]] järvestä. Tuo [[matka]] [[jätti]] minuun pysyvän jäljen.",
    translation:
      "Yesterday I read a news story in the paper that affected me strongly. It described how the climate is changing and how it concerns the whole world. The environment is an important matter to me, and I thought for a long time about what I could do. In the end I decided to travel for the weekend close to nature. " +
      "I invited two friends along and suggested that we go by train. We bought the tickets online, and the train ran at a good speed. We arrived at a small island in the afternoon. Birds flew in the sky, flowers grew on the shore, and in the distance a high mountain was visible. " +
      "In the evening we organized a small party. We listened to music and danced until late. We also discussed serious things: society, the law, and why it is worth voting. Everyone has the right to influence shared decisions. " +
      "On Sunday my body was tired, but I felt better quickly. I noticed that a healthy life is not only medicine and sport, but also nature, friends, and joy. Before the trip home I took one more photo of the lake. That trip left a lasting mark on me.",
    targets: [
      "lehti",
      "uutinen",
      "vaikuttaa",
      "kuvata",
      "ilmasto",
      "maailma",
      "ympäristö",
      "asia",
      "ajatella",
      "matkustaa",
      "luonto",
      "kutsua",
      "ystävä",
      "ehdottaa",
      "lähteä",
      "juna",
      "lippu",
      "kulkea",
      "saapua",
      "saari",
      "lentää",
      "ranta",
      "kukka",
      "vuori",
      "järjestää",
      "juhla",
      "musiikki",
      "tanssia",
      "keskustella",
      "yhteiskunta",
      "laki",
      "äänestää",
      "oikeus",
      "päätös",
      "keho",
      "parantua",
      "huomata",
      "terveellinen",
      "lääke",
      "urheilu",
      "ilo",
      "kuva",
      "matka",
      "jättää",
    ],
  },
};

export default week6;
