import type { Week } from "@/lib/content-types";

// Week 7 — third week of the Laajennus phase (weeks 5–8), pushing toward B1:
// working life & professions, money & economy, study & knowledge, mind & thinking,
// emotions & character, and time & change. The reading text uses only words that
// already exist in the corpus (Weeks 1–7).
const week7: Week = {
  week: 7,
  phase: "Laajennus",
  theme: "Työ, raha, mieli ja aika",
  days: [
    {
      day: 1,
      theme: "Ammatti ja työelämä",
      wordSlugs: [
        "ammatti",
        "työpaikka",
        "pomo",
        "kollega",
        "taito",
        "hakemus",
        "haastattelu",
        "hoitaa",
        "menestyä",
        "sopia",
        "johtaa",
        "palkata",
      ],
    },
    {
      day: 2,
      theme: "Raha ja talous",
      wordSlugs: [
        "halpa",
        "ostos",
        "tili",
        "kortti",
        "käteinen",
        "velka",
        "tulo",
        "meno",
        "myydä",
        "ansaita",
        "lainata",
        "sijoittaa",
      ],
    },
    {
      day: 3,
      theme: "Opiskelu ja tieto",
      wordSlugs: [
        "tieto",
        "yliopisto",
        "tutkinto",
        "koe",
        "läksy",
        "sivu",
        "numero",
        "opettaa",
        "tutkia",
        "harjoitella",
        "kokeilla",
        "selvittää",
      ],
    },
    {
      day: 4,
      theme: "Mieli ja ajattelu",
      wordSlugs: [
        "mieli",
        "ajatus",
        "idea",
        "muisti",
        "unelma",
        "uni",
        "järki",
        "aivot",
        "epäillä",
        "keksiä",
        "pohtia",
        "kuvitella",
      ],
    },
    {
      day: 5,
      theme: "Tunteet ja luonne",
      wordSlugs: [
        "pelätä",
        "nauraa",
        "itkeä",
        "hymyillä",
        "tylsä",
        "ujo",
        "ylpeä",
        "rauhallinen",
        "kärsivällinen",
        "hermostua",
        "pettyä",
        "nauttia",
      ],
    },
    {
      day: 6,
      theme: "Aika ja muutos",
      wordSlugs: [
        "eilen",
        "hetki",
        "menneisyys",
        "tulevaisuus",
        "kausi",
        "muutos",
        "kehitys",
        "jatkua",
        "tapahtua",
        "kestää",
        "viimeinen",
        "seuraava",
      ],
    },
  ],
  teksti: {
    title: "Uusi suunta",
    level: "B1",
    topic: "Anna kyllästyy vanhaan työhönsä, uskaltaa hakea uutta ammattia ja löytää uuden suunnan elämälleen.",
    paragraph:
      "Anna oli tehnyt samaa [[työtä]] monta [[vuotta]], mutta viime [[kausi]] oli tuntunut [[tylsältä]]. Hän [[pohti]] usein, mitä haluaisi tehdä [[tulevaisuudessa]]. [[Eilen]] hänelle tuli [[mieleen]] rohkea [[ajatus]]: ehkä olisi aika tehdä iso [[muutos]] ja vaihtaa kokonaan [[ammattia]]. " +
      "Aluksi Anna [[epäili]] itseään, koska uusi [[ala]] vaatisi lisää [[tietoa]] ja uusia [[taitoja]]. Silti hän [[päätti]] [[kokeilla]]. Hän [[harjoitteli]] [[haastattelua]] varten ja kirjoitti huolellisen [[hakemuksen]]. 'Jos en edes [[yritä]], en voi [[menestyä]]', hän [[ajatteli]]. " +
      "[[Haastattelussa]] Anna [[hermostui]] ja [[pelkäsi]], ja hänen [[kätensä]] tärisivät. Mutta uusi [[pomo]] oli [[ystävällinen]] ja [[rauhallinen]], ja pian Anna [[hymyili]]. He [[sopivat]], että Anna aloittaa [[seuraavan]] [[kuukauden]] alussa. Anna oli niin iloinen, että melkein [[itki]]. " +
      "Uudessa [[työpaikassa]] Anna [[ansaitsi]] paremmin ja [[nautti]] [[työstä]]. Vaikka alku [[kesti]] aikansa, hän [[oppi]] nopeasti. Hän jopa [[sijoitti]] osan [[palkasta]] [[tilille]] [[tulevaisuutta]] varten. Anna oli [[ylpeä]] itsestään: pieni [[idea]] oli muuttunut todeksi, ja [[unelma]] [[jatkui]].",
    translation:
      "Anna had done the same work for many years, but the last period had felt boring. She often pondered what she would like to do in the future. Yesterday a bold thought came to her mind: maybe it was time to make a big change and switch professions entirely. " +
      "At first Anna doubted herself, because a new field would require more knowledge and new skills. Still, she decided to try. She practised for the interview and wrote a careful application. 'If I don't even try, I can't succeed,' she thought. " +
      "In the interview Anna got nervous and was afraid, and her hands trembled. But the new boss was friendly and calm, and soon Anna smiled. They agreed that Anna would start at the beginning of the next month. Anna was so happy that she almost cried. " +
      "At the new workplace Anna earned more and enjoyed the work. Although the start took its time, she learned quickly. She even invested part of her salary into an account for the future. Anna was proud of herself: a small idea had become real, and the dream continued.",
    targets: [
      "työ",
      "vuosi",
      "kausi",
      "tylsä",
      "pohtia",
      "tulevaisuus",
      "eilen",
      "mieli",
      "ajatus",
      "muutos",
      "ammatti",
      "epäillä",
      "ala",
      "tieto",
      "taito",
      "päättää",
      "kokeilla",
      "harjoitella",
      "haastattelu",
      "hakemus",
      "yrittää",
      "menestyä",
      "ajatella",
      "hermostua",
      "pelätä",
      "käsi",
      "pomo",
      "ystävällinen",
      "rauhallinen",
      "hymyillä",
      "sopia",
      "seuraava",
      "kuukausi",
      "itkeä",
      "työpaikka",
      "ansaita",
      "nauttia",
      "kestää",
      "oppia",
      "sijoittaa",
      "palkka",
      "tili",
      "ylpeä",
      "idea",
      "unelma",
      "jatkua",
    ],
  },
};

export default week7;
