import type { Week } from "@/lib/content-types";

// Week 8 — final week of the Laajennus phase (weeks 5–8), consolidating everyday
// vocabulary at B1: city & traffic, home & living, food & cooking, weather & seasons,
// communication & media, and the world & travel. The reading text uses only words
// that already exist in the corpus (Weeks 1–8).
const week8: Week = {
  week: 8,
  phase: "Laajennus",
  theme: "Koti, ruoka, sää ja matkailu",
  days: [
    {
      day: 1,
      theme: "Kaupunki ja liikenne",
      wordSlugs: [
        "liikenne",
        "silta",
        "risteys",
        "pysäkki",
        "lentokenttä",
        "asukas",
        "keskusta",
        "alue",
        "kuljettaja",
        "matkustaja",
        "kartta",
        "ylittää",
      ],
    },
    {
      day: 2,
      theme: "Koti ja asuminen",
      wordSlugs: [
        "asunto",
        "kerros",
        "piha",
        "matto",
        "hylly",
        "uuni",
        "vuokra",
        "vessa",
        "parveke",
        "jääkaappi",
        "sisustus",
        "remontti",
      ],
    },
    {
      day: 3,
      theme: "Ruoka ja ruoanlaitto",
      wordSlugs: [
        "kana",
        "riisi",
        "keitto",
        "hedelmä",
        "vihannes",
        "sokeri",
        "suola",
        "nälkä",
        "maistua",
        "keittää",
        "paistaa",
        "leipoa",
      ],
    },
    {
      day: 4,
      theme: "Sää ja vuodenajat",
      wordSlugs: [
        "kesä",
        "talvi",
        "syksy",
        "kevät",
        "lämmin",
        "kuuma",
        "pakkanen",
        "myrsky",
        "sumu",
        "pilvinen",
        "aste",
        "sataa",
      ],
    },
    {
      day: 5,
      theme: "Viestintä ja media",
      wordSlugs: [
        "netti",
        "sähköposti",
        "ohjelma",
        "sivusto",
        "video",
        "salasana",
        "laite",
        "näyttö",
        "yhteys",
        "käyttäjä",
        "lähettää",
        "ladata",
      ],
    },
    {
      day: 6,
      theme: "Maailma ja matkailu",
      wordSlugs: [
        "maa",
        "loma",
        "pääkaupunki",
        "lentokone",
        "passi",
        "turisti",
        "kulttuuri",
        "kansainvälinen",
        "ulkomaalainen",
        "seikkailu",
        "tutustua",
        "varata",
      ],
    },
  ],
  teksti: {
    title: "Lomamatka ulkomaille",
    level: "B1",
    topic: "Kertoja varaa kesäloman matkan toiseen maahan ja kertoo matkasta: lennosta, asunnosta, ruoasta ja uudesta kulttuurista.",
    paragraph:
      "[[Kesällä]] päätin lähteä [[lomalle]] toiseen [[maahan]]. [[Varasin]] [[netistä]] [[liput]] ja pienen [[asunnon]] [[pääkaupungin]] [[keskustasta]]. Etsin [[sivustolta]] tietoa ja [[latasin]] puhelimeen [[kartan]]. Tarkistin myös, että [[passi]] oli voimassa, ja [[lähetin]] [[sähköpostin]] ystävälleni. " +
      "[[Lentokone]] laskeutui [[lentokentälle]], kun sää oli [[lämmin]], noin kaksikymmentä [[astetta]]. Matkalla [[keskustaan]] [[ylitimme]] korkean [[sillan]] ja näimme vilkkaan [[liikenteen]]. [[Kuljettaja]] jätti meidät [[pysäkille]]. [[Asunto]] oli kolmannessa [[kerroksessa]], ja siellä oli pieni [[parveke]], [[jääkaappi]] ja siisti [[vessa]]. " +
      "Illalla minulla oli kova [[nälkä]]. Ostin [[torilta]] [[kanaa]], [[riisiä]] ja tuoreita [[hedelmiä]] sekä muutaman [[vihanneksen]]. [[Keitin]] [[keiton]] ja [[paistoin]] kalaa. Ruoka [[maistui]] hyvältä, vaikka lisäsin vahingossa liikaa [[suolaa]] enkä yhtään [[sokeria]]. " +
      "Seuraavina päivinä [[tutustuin]] paikalliseen [[kulttuuriin]]. [[Keskusta]] oli täynnä [[turisteja]], ja tapasin myös muita [[ulkomaalaisia]]. Tämä [[kansainvälinen]] [[seikkailu]] opetti paljon uudesta [[maasta]]. Kuvasin [[videoita]] [[laitteellani]] ja [[latasin]] ne [[nettiin]] ystäville. " +
      "Kun pimeä [[talvi]] taas tulee, muistelen lämpimin mielin tätä [[kesää]] ja sitä kaukaista [[maata]]. Ehkä jo [[keväällä]] [[varaan]] uuden matkan.",
    translation:
      "In the summer I decided to go on holiday to another country. I booked the tickets online and a small apartment in the capital's centre. I looked for information on the website and downloaded a map to my phone. I also checked that my passport was valid, and sent an email to my friend. " +
      "The plane landed at the airport when the weather was warm, about twenty degrees. On the way to the centre we crossed a high bridge and saw the busy traffic. The driver left us at the bus stop. The apartment was on the third floor, and there was a small balcony, a fridge and a clean toilet. " +
      "In the evening I was very hungry. I bought chicken, rice and fresh fruit from the market, plus a few vegetables. I made soup and fried some fish. The food tasted good, although I accidentally added too much salt and no sugar at all. " +
      "Over the following days I got to know the local culture. The centre was full of tourists, and I also met other foreigners. This international adventure taught me a lot about the new country. I filmed videos with my device and uploaded them to the internet for my friends. " +
      "When the dark winter comes again, I will remember this summer and that faraway country fondly. Perhaps as early as spring I'll book a new trip.",
    targets: [
      "kesä",
      "loma",
      "maa",
      "varata",
      "netti",
      "lippu",
      "asunto",
      "pääkaupunki",
      "keskusta",
      "sivusto",
      "ladata",
      "kartta",
      "passi",
      "lähettää",
      "sähköposti",
      "lentokone",
      "lentokenttä",
      "lämmin",
      "aste",
      "ylittää",
      "silta",
      "liikenne",
      "kuljettaja",
      "pysäkki",
      "kerros",
      "parveke",
      "jääkaappi",
      "vessa",
      "nälkä",
      "tori",
      "kana",
      "riisi",
      "hedelmä",
      "vihannes",
      "keittää",
      "keitto",
      "paistaa",
      "maistua",
      "suola",
      "sokeri",
      "tutustua",
      "kulttuuri",
      "turisti",
      "ulkomaalainen",
      "kansainvälinen",
      "seikkailu",
      "video",
      "laite",
      "talvi",
      "kevät",
    ],
  },
};

export default week8;
