import type { Week } from "@/lib/content-types";

// Week 9 — first week of the Sujuvuus phase (weeks 9–13), moving from concrete
// everyday vocabulary toward more abstract B1–B2 fluency: opinions & reasoning,
// problems & solutions, plans & goals, time & sequence, comparison & quantity,
// and communication & interaction. The reading text uses only words that already
// exist in the corpus (Weeks 1–9).
const week9: Week = {
  week: 9,
  phase: "Sujuvuus",
  theme: "Mielipiteet, tavoitteet ja vuorovaikutus",
  days: [
    {
      day: 1,
      theme: "Mielipide ja perustelu",
      wordSlugs: [
        "mielipide",
        "näkemys",
        "perustella",
        "väittää",
        "arvostaa",
        "kannattaa",
        "vastustaa",
        "myöntää",
        "kieltää",
        "suostua",
        "huomauttaa",
        "puolustaa",
      ],
    },
    {
      day: 2,
      theme: "Ongelma ja ratkaisu",
      wordSlugs: [
        "ratkaisu",
        "ratkaista",
        "vaikeus",
        "este",
        "haaste",
        "seuraus",
        "aiheuttaa",
        "välttää",
        "onnistua",
        "epäonnistua",
        "selvitä",
        "ehkäistä",
      ],
    },
    {
      day: 3,
      theme: "Suunnitelma ja tavoite",
      wordSlugs: [
        "suunnitelma",
        "suunnitella",
        "tavoite",
        "tarkoitus",
        "valmistautua",
        "saavuttaa",
        "toteuttaa",
        "aikoa",
        "pyrkiä",
        "edetä",
        "keskittyä",
        "päämäärä",
      ],
    },
    {
      day: 4,
      theme: "Aika, järjestys ja kesto",
      wordSlugs: [
        "vaihe",
        "jakso",
        "nykyään",
        "aikaisemmin",
        "myöhemmin",
        "lopulta",
        "vihdoin",
        "jatkuvasti",
        "välillä",
        "toistua",
        "jatkossa",
        "ajoissa",
      ],
    },
    {
      day: 5,
      theme: "Vertailu ja määrä",
      wordSlugs: [
        "erota",
        "verrata",
        "samanlainen",
        "erilainen",
        "vastaava",
        "määrä",
        "osuus",
        "lisääntyä",
        "vähentyä",
        "riittävä",
        "enemmistö",
        "keskimäärin",
      ],
    },
    {
      day: 6,
      theme: "Viestintä ja vuorovaikutus",
      wordSlugs: [
        "ilmaista",
        "viitata",
        "vakuuttaa",
        "neuvotella",
        "vaihtaa",
        "esitellä",
        "tarkentaa",
        "korostaa",
        "keskeyttää",
        "vastaanottaa",
        "mainostaa",
        "kuvailla",
      ],
    },
  ],
  teksti: {
    title: "Yhteinen päätös",
    level: "B1",
    topic: "Kerhon kokouksessa jäsenet kohtaavat ongelman, esittävät erilaisia mielipiteitä, neuvottelevat ja päätyvät lopulta yhteiseen ratkaisuun.",
    paragraph:
      "Kerhomme kevään [[kokous]] alkoi vaikeasta [[asiasta]]. Jäsenten [[määrä]] oli [[vähentynyt]] [[jatkuvasti]], ja huoli oli [[lisääntynyt]] samaa tahtia. Puheenjohtaja [[esitteli]] [[ongelman]] selkeästi ja [[korosti]], että jokin [[muutos]] oli tarpeen. 'Jos emme tee mitään [[ajoissa]], sama [[tilanne]] [[toistuu]] [[jatkossa]]', hän [[huomautti]]. " +
      "Jokaisella oli oma [[mielipide]]. Osa [[kannatti]] uutta [[suunnitelmaa]], toiset taas [[vastustivat]] sitä. Yksi jäsen [[ilmaisi]] [[näkemyksensä]] rohkeasti ja [[perusteli]] sen hyvin. Toinen [[väitti]], että [[aikaisemmin]] tehty [[ratkaisu]] oli toiminut paremmin, ja [[puolusti]] sitkeästi vanhaa tapaa. [[Välillä]] [[keskustelimme]] kiivaasti, ja joku jopa [[keskeytti]] puhujan. " +
      "Puheenjohtaja pyysi kaikkia [[keskittymään]] olennaiseen. Aloimme [[neuvotella]] rauhallisesti ja [[verrata]] [[erilaisia]] ehdotuksia. Yksi jäsen [[kuvaili]], miten [[vastaava]] kerho oli [[onnistunut]] toisella paikkakunnalla, ja [[viittasi]] heidän kokemuksiinsa. Pian huomasimme, että monet [[näkemykset]] olivat itse asiassa hyvin [[samanlaisia]] eivätkä [[eronneet]] paljon toisistaan. " +
      "Kun [[keskityimme]] yhteiseen [[tavoitteeseen]], [[etenimme]] nopeammin. Puheenjohtaja [[tarkensi]] [[suunnitelmaa]] ja [[vakuutti]], että sen voi [[toteuttaa]] pienin kustannuksin. [[Tarkoituksena]] oli [[ehkäistä]] jäsenmäärän lasku ja [[pyrkiä]] saamaan uusia jäseniä. Päätimme [[mainostaa]] kerhoa enemmän ja [[valmistautua]] [[seuraavaan]] [[jaksoon]] huolellisesti. " +
      "[[Lopulta]] [[enemmistö]] [[suostui]] [[ratkaisuun]], joka [[vaikutti]] [[riittävän]] hyvältä. Nekin, jotka olivat [[vastustaneet]] suunnitelmaa, [[myönsivät]], että sitä [[kannatti]] kokeilla. [[Myöhemmin]] samana vuonna jäsenten määrä alkoi taas kasvaa. [[Vihdoin]] olimme [[saavuttaneet]] [[päämäärämme]]. Opimme, että vaikeakin [[haaste]] on mahdollista [[ratkaista]], kun kaikki [[arvostavat]] toistensa mielipiteitä ja [[pyrkivät]] samaan [[päämäärään]].",
    translation:
      "Our club's spring meeting began with a difficult matter. The number of members had been decreasing continuously, and worry had grown at the same pace. The chair presented the problem clearly and stressed that some change was needed. 'If we don't do anything in time, the same situation will recur in the future,' he remarked. " +
      "Everyone had their own opinion. Some supported the new plan, while others opposed it. One member expressed his view boldly and justified it well. Another claimed that the solution made earlier had worked better, and stubbornly defended the old way. At times we discussed heatedly, and someone even interrupted the speaker. " +
      "The chair asked everyone to concentrate on the essentials. We began to negotiate calmly and to compare different proposals. One member described how a similar club had succeeded in another town, and referred to their experiences. Soon we noticed that many of the views were in fact very similar and did not differ much from one another. " +
      "When we focused on the common goal, we made progress faster. The chair refined the plan and assured us that it could be carried out at little cost. The intention was to prevent the drop in membership and to strive to get new members. We decided to advertise the club more and to prepare carefully for the next period. " +
      "In the end the majority agreed to a solution that seemed good enough. Even those who had opposed the plan admitted that it was worth trying. Later that year the number of members began to grow again. At last we had reached our goal. We learned that even a difficult challenge can be solved when everyone values each other's opinions and strives toward the same aim.",
    targets: [
      "kokous",
      "asia",
      "määrä",
      "vähentyä",
      "jatkuvasti",
      "lisääntyä",
      "esitellä",
      "ongelma",
      "korostaa",
      "muutos",
      "ajoissa",
      "tilanne",
      "toistua",
      "jatkossa",
      "huomauttaa",
      "mielipide",
      "kannattaa",
      "suunnitelma",
      "vastustaa",
      "ilmaista",
      "näkemys",
      "perustella",
      "väittää",
      "aikaisemmin",
      "ratkaisu",
      "puolustaa",
      "välillä",
      "keskustella",
      "keskeyttää",
      "keskittyä",
      "neuvotella",
      "verrata",
      "erilainen",
      "kuvailla",
      "vastaava",
      "onnistua",
      "viitata",
      "samanlainen",
      "erota",
      "tavoite",
      "edetä",
      "tarkentaa",
      "vakuuttaa",
      "toteuttaa",
      "tarkoitus",
      "ehkäistä",
      "pyrkiä",
      "mainostaa",
      "valmistautua",
      "seuraava",
      "jakso",
      "lopulta",
      "enemmistö",
      "suostua",
      "vaikuttaa",
      "riittävä",
      "myöntää",
      "myöhemmin",
      "vihdoin",
      "saavuttaa",
      "päämäärä",
      "haaste",
      "ratkaista",
      "arvostaa",
    ],
  },
};

export default week9;
